name: CI

on:
  push:
    branches:
    - master
    
jobs:
  build:

    runs-on: macos
    
    steps:
    - uses: actions/checkout@v1
    - name: Publish to CocoaPod register
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push SOPullUpView.podspec --skip-import-validation --allow-warnings
